@startuml 物理IO设计


interface BasicSourceObj <<资源对象处理接口>> {
  +SourceObj createOne(SourceObj sourceObj) // 创建一个资源对象,如果设置了物理io等需要做额外处理
  +SourceObj refSourceObj(SourceObj source,RefSourceObj ref) // 关联一个资源对象
  +SourceObj refSourceObj(SourceObj source,List<RefSourceObj> ref) // 关联多个资源对象
  +SourceObj updateSourceObj(SourceObj sourceObj) // 更新资源对象信息
  +JudgeObj createJudge(List<SourceObj> sourceObj) // 创建一个空的片段对象
  +JudgeObj createJudge(List<SourceObj> sourceObj,JudgeObj judgeObj) // 在该片段对象下面追加一个
  +List<JudgeObj> analysisJudge(List<SourceObj> sourceObj) // 解析某个资源对象中的所有片段（单层）
  +Boolean deleteSourceObj(SourceObj) // 删除某个资源对象

}

interface BasicIoObj <<基础IO能力>> {
  +IoObj create(SourcePath sourcePath,IoTypeEnum ioType) // 创建一个Io对象
  +List<DataCopies> getByIoObj(SourcePath sourcePath) //获取数据副本
  +void getByIoObj(IoObj ioObj)// 获取并填充数据副本
  +flushIoObj(IoObj ioObj)// 刷新数据副本（写入内存的，并合并磁盘改动）
  +saveIoObj(IoObj ioObj)// 覆盖数据副本（直接以内存为准）
  +deleteIoObj(IoObj ioObj)// 删除某一个物理操作对象
}